services:
  sanka-skepp:
    build: .

    image: sanka-skepp:latest

    container_name: sanka-skepp

    restart: unless-stopped

    ports:
      - "3011:80"

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 3
